trigger:
  - main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install & Build React App'

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'ftp.retrotreasures.in'  # change to your actual domain
      username: '$(ftpUsername)'
      password: '$(ftpPassword)'
      rootDirectory: '$(System.DefaultWorkingDirectory)/build'
      remoteDirectory: '/public_html'  # or your correct folder
      clean: false
    displayName: 'FTP Deploy to GoDaddy'
